package com.example.data

import android.util.Log
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiService {
    private const val TAG = "GeminiService"
    
    private val client by lazy {
        OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .build()
    }

    private val jsonMediaType = "application/json; charset=utf-8".toMediaType()

    // Helper to check if API key exists
    fun isApiKeyAvailable(): Boolean {
        val key = BuildConfig.GEMINI_API_KEY
        return !key.isNullOrEmpty() && key != "MY_GEMINI_API_KEY"
    }

    suspend fun generateContent(prompt: String, systemInstruction: String? = null): String = withContext(Dispatchers.IO) {
        if (!isApiKeyAvailable()) {
            Log.w(TAG, "Gemini API key is not configured. Falling back to local responses.")
            return@withContext getLocalFallbackResponse(prompt)
        }

        try {
            val key = BuildConfig.GEMINI_API_KEY
            val url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=$key"

            val contentsArray = JSONArray().apply {
                put(JSONObject().apply {
                    put("parts", JSONArray().apply {
                        put(JSONObject().apply {
                            put("text", prompt)
                        })
                    })
                })
            }

            val requestBodyJson = JSONObject().apply {
                put("contents", contentsArray)
                
                if (systemInstruction != null) {
                    put("systemInstruction", JSONObject().apply {
                        put("parts", JSONArray().apply {
                            put(JSONObject().apply {
                                put("text", systemInstruction)
                            })
                        })
                    })
                }
                
                put("generationConfig", JSONObject().apply {
                    put("temperature", 0.7)
                })
            }

            val request = Request.Builder()
                .url(url)
                .post(requestBodyJson.toString().toRequestBody(jsonMediaType))
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    val errorMsg = response.body?.string() ?: "Unknown error"
                    Log.e(TAG, "Gemini API request failed: Code ${response.code} - $errorMsg")
                    return@withContext "Error: Request failed with code ${response.code}. Please ensure your API key is correct."
                }

                val responseBody = response.body?.string() ?: return@withContext "Error: Empty response body."
                val jsonObject = JSONObject(responseBody)
                val candidates = jsonObject.optJSONArray("candidates")
                if (candidates != null && candidates.length() > 0) {
                    val firstCandidate = candidates.getJSONObject(0)
                    val contentObj = firstCandidate.optJSONObject("content")
                    if (contentObj != null) {
                        val parts = contentObj.optJSONArray("parts")
                        if (parts != null && parts.length() > 0) {
                            return@withContext parts.getJSONObject(0).optString("text", "No text found.")
                        }
                    }
                }
                return@withContext "No response generated by Gemini."
            }
        } catch (e: Exception) {
            Log.e(TAG, "Gemini call exception", e)
            return@withContext "Connection failed: ${e.message}. Running in offline simulation mode."
        }
    }

    /**
     * Parse system generated response for video ideation or content optimizations
     */
    suspend fun getOptimizedMetadata(ideaOutline: String, category: String): Pair<String, String> {
        val systemPrompt = "You are MobileTube's AI Growth Partner. Given a basic video outline and category, generate a highly engaging, viral, high RPM optimized Video Title AND an immersive, SEO-friendly Description that includes hashtags and revenue call-to-actions. Format your response EXACTLY as: TITLE: <optimized title> \nDESCRIPTION: <optimized description>"
        val userPrompt = "Category: $category\nOutline: $ideaOutline"
        
        val response = generateContent(userPrompt, systemPrompt)
        
        return try {
            if (response.startsWith("Error:") || response.startsWith("Connection failed:") || response.contains("offline simulation")) {
                // Return static simulation
                throw Exception("Fallback needed")
            }
            
            val titleMarker = "TITLE:"
            val descMarker = "DESCRIPTION:"
            
            var title = ""
            var desc = ""
            
            if (response.contains(titleMarker) && response.contains(descMarker)) {
                val titleIndex = response.indexOf(titleMarker)
                val descIndex = response.indexOf(descMarker)
                
                if (titleIndex < descIndex) {
                    title = response.substring(titleIndex + titleMarker.length, descIndex).trim()
                    desc = response.substring(descIndex + descMarker.length).trim()
                } else {
                    desc = response.substring(descIndex + descMarker.length, titleIndex).trim()
                    title = response.substring(titleIndex + titleMarker.length).trim()
                }
            } else {
                val lines = response.lines().filter { it.isNotBlank() }
                title = lines.firstOrNull()?.replace("Title:", "", true)?.trim() ?: "AI Video on $ideaOutline"
                desc = lines.drop(1).joinToString("\n").replace("Description:", "", true)?.trim() ?: "Custom creator upload optimized by MobileTube AI."
            }
            
            Pair(title, desc)
        } catch (e: Exception) {
            // Local fallback simulation
            val fallbackTitle = "How I Mastered $ideaOutline in 30 Days (Complete Guide)"
            val fallbackDesc = "Welcome back to MobileTube! 🚀 In today's video, we are diving deep into the world of $category, focusing specifically on: $ideaOutline.\n\nDon't forget to LIKE and SUBSCRIBE for more weekly growth hacks!\n\n#$category #$ideaOutline #MobileTube"
            Pair(fallbackTitle, fallbackDesc)
        }
    }

    /**
     * Generate an automated engagement reply for channel comments
     */
    suspend fun generateAutoReply(commentText: String, commenterName: String): String {
        val systemPrompt = "You are a professional MobileTube content creator. Draft a short, warm, highly appreciative, and engaging reply to a subscriber comment."
        val userPrompt = "Comment from $commenterName: \"$commentText\""
        
        val response = generateContent(userPrompt, systemPrompt)
        
        if (response.startsWith("Error:") || response.startsWith("Connection failed:") || response.contains("offline simulation")) {
            return "Thank you so much for the support, $commenterName! Stay tuned for more amazing content coming soon. 🚀"
        }
        return response.trim()
    }

    /**
     * Generate a direct message chat response from a content creator to a user
     */
    suspend fun generateDirectChatReply(messageText: String, senderName: String, creatorName: String): String {
        val systemPrompt = "You are $creatorName, a popular video creator on MobileTube. Chat directly in direct messaging with a viewer named $senderName. Write a lively, ultra-short, friendly reply of 1-2 lines. Be incredibly conversational and use emojis. Keep it casual!"
        val userPrompt = "$senderName says: \"$messageText\""
        
        val response = generateContent(userPrompt, systemPrompt)
        
        if (response.startsWith("Error:") || response.startsWith("Connection failed:") || response.contains("offline simulation")) {
            val genericReplies = listOf(
                "Hey $senderName! Thanks so much for reaching out! Really appreciate you watching my streams. Keep rockin'! 🚀",
                "Hi there! So glad you liked the latest upload. Let me know what you think of the new features! 🙌",
                "Yo $senderName! Appreciate the support. I'm actually editing a new video right now, can't wait for you to see it! 🎬",
                "Thanks, $senderName! Means a lot. Have an awesome day! ✨"
            )
            return genericReplies.random()
        }
        return response.trim()
    }

    /**
     * Provide offline fallback response templates
     */
    private fun getLocalFallbackResponse(prompt: String): String {
        return when {
            prompt.contains("Lofi", true) || prompt.contains("Music", true) -> {
                "TITLE: 🎧 Deep Focus Lofi Beats - Chill Instrumental Playlist to Study & Code to\n" +
                "DESCRIPTION: Stream our handpicked collection of calming lofi songs. Perfect for concentration, coding, studying, and relaxation.\n\n#lofi #studymusic #chill"
            }
            prompt.contains("Coding", true) || prompt.contains("Tech", true) -> {
                "TITLE: 💻 Modern Jetpack Compose & Clean Architecture Masterclass (2026)\n" +
                "DESCRIPTION: Master state propagation, reactive flows, and beautiful UI designs using Jetpack Compose and Room databases.\n\n#compose #kotlin #cleanarchitecture"
            }
            else -> {
                "TITLE: 🚀 The Next Big Thing in Mobile Video Ecosystems (MobileTube Exclusive)\n" +
                "DESCRIPTION: A thorough breakdown of how MobileTube is changing content creation, giving power back to creators with direct community monetizations.\n\n#creators #mobiletube #fintech"
            }
        }
    }
}
